---
# Changes here will be overwritten by Copier
_commit: '5600844'
_src_path: .
base_answers_file: .datarobot/answers/base.yml
copyright_year: 2025
fastmcp_app_name: mcp_deployments
fastmcp_local_port: 8000
mcp_template_framework: base_with_tools
