[pytest]
filterwarnings =
    ignore::DeprecationWarning 
addopts = --cov=. --cov-config=.coveragerc --cov-report=term-missing --cov-fail-under=90
pythonpath = 
    .
testpaths =
    app/tests/unit
    app/tests/integration
    app/tests/ete
python_files = test_*.py
python_functions = test_*
