---
pipeline:
  name: Test FastMCP Component
  identifier: Build_af_component_fastmcp_backend_1752223405520
  projectIdentifier: afcomponentfastmcpbackend
  orgIdentifier: buzok
  stages:
    - parallel:
        - stage:
            name: Test FastMCP Base
            identifier: Test_Component_FastMCP_Base
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: Copy with copier and install dependencies
                      identifier: Install_dependencies_and_copy_with_copier
                      spec:
                        connectorRef: GHCR_HHI
                        image: ghcr.io/astral-sh/uv:<+matrix.python>-bookworm
                        shell: Sh
                        command: |-
                          apt-get update && apt-get install -y git build-essential
                          uvx copier copy . ./copier_context_base_<+matrix.python> --data mcp_template_framework=base --defaults
                          cd ./copier_context_base_<+matrix.python>/mcp_server
                          uvx --from go-task-bin task install
                        envVariables:
                          UV_CACHE_DIR: /.uv_cache
                          UV_PYTHON: <+matrix.python>
                  - parallel:
                      - step:
                          type: Run
                          name: Linter
                          identifier: Linter
                          spec:
                            connectorRef: GHCR_HHI
                            image: ghcr.io/astral-sh/uv:<+matrix.python>-bookworm
                            shell: Sh
                            command: |-
                              cd ./copier_context_base_<+matrix.python>/mcp_server
                              uvx --from go-task-bin task lint-check
                            envVariables:
                              UV_CACHE_DIR: /.uv_cache
                              UV_PYTHON: <+matrix.python>
                      - step:
                          type: Run
                          name: Unit Tests
                          identifier: Unit_Tests
                          spec:
                            connectorRef: GHCR_HHI
                            image: ghcr.io/astral-sh/uv:<+matrix.python>-bookworm
                            shell: Sh
                            command: |-
                              cd ./copier_context_base_<+matrix.python>/mcp_server
                              uvx --from go-task-bin task unit
                            envVariables:
                              UV_CACHE_DIR: /.uv_cache
                              UV_PYTHON: <+matrix.python>
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              caching:
                enabled: true
                paths:
                  - /.uv_cache
                  - /var/cache/apt/archives
                  - /var/lib/apt/lists
              buildIntelligence:
                enabled: true
              sharedPaths:
                - /.uv_cache
                - /var/cache/apt/archives
                - /var/lib/apt/lists
            strategy:
              matrix:
                python:
                  - python3.11
                  - python3.12
                  - python3.13
                nodeName: <+matrix.python>
        - stage:
            name: Test FastMCP BaseWithTools
            identifier: Test_Component_FastMCP_BaseWithTools
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: Copy with copier and install dependencies
                      identifier: Install_dependencies_and_copy_with_copier
                      spec:
                        connectorRef: GHCR_HHI
                        image: ghcr.io/astral-sh/uv:<+matrix.python>-bookworm
                        shell: Sh
                        command: |-
                          apt-get update && apt-get install -y git build-essential
                          uvx copier copy . ./copier_context_tools_<+matrix.python> --data mcp_template_framework=base_with_tools --defaults
                          cd ./copier_context_tools_<+matrix.python>/mcp_server
                          uvx --from go-task-bin task install
                        envVariables:
                          UV_CACHE_DIR: /.uv_cache
                          UV_PYTHON: <+matrix.python>
                  - parallel:
                      - step:
                          type: Run
                          name: Linter
                          identifier: Linter
                          spec:
                            connectorRef: GHCR_HHI
                            image: ghcr.io/astral-sh/uv:<+matrix.python>-bookworm
                            shell: Sh
                            command: |-
                              cd ./copier_context_tools_<+matrix.python>/mcp_server
                              uvx --from go-task-bin task lint-check
                            envVariables:
                              UV_CACHE_DIR: /.uv_cache
                              UV_PYTHON: <+matrix.python>
                      - step:
                          type: Run
                          name: Unit Tests
                          identifier: Unit_Tests
                          spec:
                            connectorRef: GHCR_HHI
                            image: ghcr.io/astral-sh/uv:<+matrix.python>-bookworm
                            shell: Sh
                            command: |-
                              cd ./copier_context_tools_<+matrix.python>/mcp_server
                              uvx --from go-task-bin task unit
                            envVariables:
                              UV_CACHE_DIR: /.uv_cache
                              UV_PYTHON: <+matrix.python>
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              caching:
                enabled: true
                paths:
                  - /.uv_cache
                  - /var/cache/apt/archives
                  - /var/lib/apt/lists
              buildIntelligence:
                enabled: true
              sharedPaths:
                - /.uv_cache
                - /var/cache/apt/archives
                - /var/lib/apt/lists
            strategy:
              matrix:
                python:
                  - python3.11
                  - python3.12
                  - python3.13
                nodeName: <+matrix.python>
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: af-component-fastmcp-backend
        build: <+input>
        sparseCheckout: []
